-- 主表
CREATE TABLE `$basic_table` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `modelid` smallint(5) unsigned NOT NULL default '0',
  `catid` smallint(5) unsigned NOT NULL default '0',
  `title` char(80) NOT NULL default '',
  `keywords` char(40) NOT NULL default '',
  `description` char(255) NOT NULL default '',
  `posids` tinyint(1) unsigned NOT NULL default '0',
  `thumb` char(100) NOT NULL default '',
  `islink` tinyint(1) unsigned NOT NULL default '0',
  `url` char(100) NOT NULL,
  `listorder` tinyint(3) unsigned NOT NULL default '0',
  `status` tinyint(2) unsigned NOT NULL default '1',
  `username` char(20) NOT NULL,
  `inputtime` int(10) unsigned NOT NULL default '0',
  `updatetime` int(10) unsigned NOT NULL default '0',
  `view` varchar(30) NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `status` (`status`,`listorder`,`id`),
  KEY `listorder` (`catid`,`status`,`listorder`,`id`),
  KEY `catid` (`catid`,`status`,`id`)
) TYPE=MyISAM;

INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'catid', '栏目', '', '', 1, 6, '/^[0-9]{1,6}$/', '请选择栏目', 'catid', 'a:1:{s:12:"defaultvalue";s:0:"";}', '', '-99', '-99', 0, 0, 1, 1, 1, 0, 0, 10, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'title', '标题', '', 'inputtitle', 1, 80, '', '请输入标题', 'title', 'a:0:{}', '', '', '', 0, 0, 1, 1, 1, 1, 1, 20, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'keywords', '关键词', '多关键词之间用空格或者“,”隔开', '', 0, 40, '', '', 'keyword', 'a:2:{s:4:"size";s:3:"100";s:12:"defaultvalue";s:0:"";}', '', '-99', '-99', 0, 0, 1, 1, 1, 1, 0, 30, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'description', '摘要', '', '', 0, 255, '', '', 'textarea', 'a:4:{s:5:"width";s:2:"98";s:6:"height";s:2:"46";s:12:"defaultvalue";s:0:"";s:10:"enablehtml";s:1:"0";}', '', '', '', 0, 0, 1, 0, 1, 1, 1, 40, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'posids', '推荐位', '', '', 0, 0, '', '', 'posid', 'a:2:{s:4:"cols";s:1:"4";s:5:"width";s:3:"125";}', '', '', '', 0, 0, 1, 0, 0, 0, 0, 70, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'islink', '转向链接', '', '', 0, 0, '', '', 'islink', 'a:1:{s:4:"size";s:2:"50";}', '', '', '', 0, 0, 1, 0, 1, 0, 0, 60, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'inputtime', '发布时间', '', '', 0, 0, '', '', 'datetime', 'a:3:{s:9:"fieldtype";s:3:"int";s:6:"format";s:11:"Y-m-d H:i:s";s:11:"defaulttype";s:1:"0";}', '', '', '', 0, 0, 0, 0, 0, 0, 1, 80, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'updatetime', '更新时间', '', '', 0, 0, '', '', 'datetime', 'a:4:{s:10:"dateformat";s:3:"int";s:6:"format";s:11:"Y-m-d H:i:s";s:11:"defaulttype";s:1:"1";s:12:"defaultvalue";s:0:"";}', '', '', '', 1, 0, 1, 0, 0, 0, 0, 90, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'thumb', '缩略图', '', '', 0, 100, '', '', 'image', 'a:9:{s:4:"size";s:2:"50";s:12:"defaultvalue";s:0:"";s:9:"show_type";s:1:"1";s:14:"upload_maxsize";s:4:"1024";s:15:"upload_allowext";s:20:"jpg|jpeg|gif|png|bmp";s:9:"watermark";s:1:"0";s:13:"isselectimage";s:1:"1";s:12:"images_width";s:0:"";s:13:"images_height";s:0:"";}', '', '', '', 0, 0, 0, 0, 1, 0, 1, 50, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'url', 'URL', '', '', 0, 100, '', '', 'text', 'a:0:{}', '', '', '', 1, 0, 1, 0, 0, 0, 0, 100, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'listorder', '排序', '', '', 0, 6, '', '', 'number', 'a:0:{}', '', '', '', 1, 0, 1, 0, 0, 0, 0, 110, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'status', '状态', '', '', 0, 2, '', '', 'box', 'a:0:{}', '', '', '', 1, 0, 1, 0, 0, 0, 0, 120, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'username', '用户名', '', '', 0, 20, '', '', 'text', 'a:0:{}', '', '', '', 1, 0, 1, 0, 0, 0, 0, 130, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'view', '内容页模板', '', '', 0, 30, '', '', 'view', 'a:2:{s:4:"size";s:0:"";s:12:"defaultvalue";s:0:"";}', '', '-99', '-99', 0, 0, 0, 0, 0, 0, 0, 140, 0);