-- 主表
CREATE TABLE `$basic_table` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `modelid` smallint(5) unsigned NOT NULL default '0',
  `catid` smallint(5) unsigned NOT NULL default '0',
  `title` char(80) NOT NULL default '',
  `keywords` char(40) NOT NULL default '',
  `description` char(255) NOT NULL default '',
  `posids` tinyint(1) unsigned NOT NULL default '0',
  `thumb` char(100) NOT NULL default '',
  `islink` tinyint(1) unsigned NOT NULL default '0',
  `url` char(100) NOT NULL,
  `listorder` tinyint(3) unsigned NOT NULL default '0',
  `status` tinyint(2) unsigned NOT NULL default '1',
  `username` char(20) NOT NULL,
  `inputtime` int(10) unsigned NOT NULL default '0',
  `updatetime` int(10) unsigned NOT NULL default '0',
  `view` varchar(30) NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `status` (`status`,`listorder`,`id`),
  KEY `listorder` (`catid`,`status`,`listorder`,`id`),
  KEY `catid` (`catid`,`status`,`id`)
) TYPE=MyISAM;

INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'catid', '栏目', '', '', 1, 6, '/^[0-9]{1,6}$/', '请选择栏目', 'catid', '{"defaultvalue":""}', '', '-99', '-99', 0, 0, 1, 1, 1, 0, 0, 10, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'title', '标题', '', 'inputtitle', 1, 80, '', '请输入标题', 'title', '[]', '', '', '', 0, 0, 1, 1, 1, 1, 1, 20, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'keywords', '关键词', '多关键词之间用空格或者“,”隔开', '', 0, 40, '', '', 'keyword', '{"size":"100","defaultvalue":""}', '', '-99', '-99', 0, 0, 1, 1, 1, 1, 0, 30, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'description', '摘要', '', '', 0, 255, '', '', 'textarea', '{"width":"98","height":"46","defaultvalue":"","enablehtml":"0"}', '', '', '', 0, 0, 1, 0, 1, 1, 1, 40, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'posids', '推荐位', '', '', 0, 0, '', '', 'posid', '{"cols":"4","width":"125"}', '', '', '', 0, 0, 1, 0, 0, 0, 0, 70, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'islink', '转向链接', '', '', 0, 0, '', '', 'islink', '{"size":"50"}', '', '', '', 0, 0, 1, 0, 1, 0, 0, 60, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'inputtime', '发布时间', '', '', 0, 0, '', '', 'datetime', '{"fieldtype":"int","format":"Y-m-d H:i:s","defaulttype":"0"}', '', '', '', 0, 0, 0, 0, 0, 0, 1, 80, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'updatetime', '更新时间', '', '', 0, 0, '', '', 'datetime', '{"dateformat":"int","format":"Y-m-d H:i:s","defaulttype":"1","defaultvalue":""}', '', '', '', 1, 0, 1, 0, 0, 0, 0, 90, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'thumb', '缩略图', '', '', 0, 100, '', '', 'image', '{"size":"50","defaultvalue":"","show_type":"1","upload_maxsize":"1024","upload_allowext":"jpg|jpeg|gif|png|bmp","watermark":"0","isselectimage":"1","images_width":"","images_height":""}', '', '', '', 0, 0, 0, 0, 1, 0, 1, 50, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'url', 'URL', '', '', 0, 100, '', '', 'text', '[]', '', '', '', 1, 0, 1, 0, 0, 0, 0, 100, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'listorder', '排序', '', '', 0, 6, '', '', 'number', '[]', '', '', '', 1, 0, 1, 0, 0, 0, 0, 110, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'status', '状态', '', '', 0, 2, '', '', 'box', '[]', '', '', '', 1, 0, 1, 0, 0, 0, 0, 120, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'username', '用户名', '', '', 0, 20, '', '', 'text', '[]', '', '', '', 1, 0, 1, 0, 0, 0, 0, 130, 0);
INSERT INTO `$base_model_field` (`modelid`, `siteid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `unsetgroupids`, `unsetroleids`, `iscore`, `isunique`, `isbase`, `issearch`, `isadd`, `isfulltext`, `isposition`, `listorder`, `disabled`) VALUES(0, $siteid, 'view', '内容页模板', '', '', 0, 30, '', '', 'view', '{"size":"","defaultvalue":""}', '', '-99', '-99', 0, 0, 0, 0, 0, 0, 0, 140, 0);